services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ..:/AlphaB:cached
    ports:
      - 8080:8080
    command: bash -c "sleep infinity"
